export default [
  {
    icon: 'user',
    title: '学生管理',
    router: '/student',
    path: '/views/student/Student.vue',
    order: 1,
  },
  {
    icon: 'user',
    title: '教师管理',
    router: '/teacher',
    path: '/views/teacher/Teacher.vue',
    order: 2,
  },
  {
    icon: 'user',
    title: '家长管理',
    router: '/parent',
    path: '/views/parent/Parent.vue',
    order: 3,
  },
  {
    icon: 'user',
    title: '学期管理',
    router: '/term',
    path: '/views/term/Term.vue',
    order: 4,
  },
  {
    icon: 'user',
    title: '班级管理',
    router: '/class',
    path: '/views/class/Class.vue',
    order: 5,
  },
  {
    icon: 'user',
    title: '课程管理',
    router: '/course',
    path: '/views/course/Course.vue',
    order: 6,
  },
  {
    icon: 'user',
    title: '成绩管理',
    router: '/grade',
    path: '/views/grade/Grade.vue',
    order: 3,
  },
  {
    icon: 'user',
    title: '公告管理',
    router: '/release',
    path: '/views/release/Release.vue',
    order: 3,
  },
  {
    icon: 'user',
    title: '反馈管理',
    router: '/feedback',
    path: '/views/feedback/Feedback.vue',
    order: 3,
  },
];
